// Code generated by protoc-gen-go. DO NOT EDIT.
// source: til_service.proto

/*
Package til is a generated protocol buffer package.

It is generated from these files:
	til_service.proto

It has these top-level messages:
	Note
	NotePreview
	Pagination
	PingRequest
	PingResponse
	CreateNoteRequest
	GetNotePreviewsRequest
	GetNotePreviewsResponse
*/
package til

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Note struct {
	Id        int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Note      string                      `protobuf:"bytes,3,opt,name=note" json:"note,omitempty"`
	Filename  string                      `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Note) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Note) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Note) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Note) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Note) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type NotePreview struct {
	Id          int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NotePreview string                      `protobuf:"bytes,3,opt,name=note_preview,json=notePreview" json:"note_preview,omitempty"`
	Filename    string                      `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	CreatedAt   *google_protobuf1.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt   *google_protobuf1.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *NotePreview) Reset()                    { *m = NotePreview{} }
func (m *NotePreview) String() string            { return proto.CompactTextString(m) }
func (*NotePreview) ProtoMessage()               {}
func (*NotePreview) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NotePreview) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotePreview) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NotePreview) GetNotePreview() string {
	if m != nil {
		return m.NotePreview
	}
	return ""
}

func (m *NotePreview) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *NotePreview) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *NotePreview) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Pagination struct {
	PageNumber int64 `protobuf:"varint,1,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	PerPage    int32 `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pagination) GetPageNumber() int64 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Pagination) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PingResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type CreateNoteRequest struct {
	Note *Note `protobuf:"bytes,1,opt,name=note" json:"note,omitempty"`
}

func (m *CreateNoteRequest) Reset()                    { *m = CreateNoteRequest{} }
func (m *CreateNoteRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNoteRequest) ProtoMessage()               {}
func (*CreateNoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateNoteRequest) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type GetNotePreviewsRequest struct {
	Pagination *Pagination `protobuf:"bytes,20,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *GetNotePreviewsRequest) Reset()                    { *m = GetNotePreviewsRequest{} }
func (m *GetNotePreviewsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNotePreviewsRequest) ProtoMessage()               {}
func (*GetNotePreviewsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetNotePreviewsRequest) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetNotePreviewsResponse struct {
	NotePreviews []*NotePreview `protobuf:"bytes,1,rep,name=note_previews,json=notePreviews" json:"note_previews,omitempty"`
	Pagination   *Pagination    `protobuf:"bytes,20,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *GetNotePreviewsResponse) Reset()                    { *m = GetNotePreviewsResponse{} }
func (m *GetNotePreviewsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNotePreviewsResponse) ProtoMessage()               {}
func (*GetNotePreviewsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetNotePreviewsResponse) GetNotePreviews() []*NotePreview {
	if m != nil {
		return m.NotePreviews
	}
	return nil
}

func (m *GetNotePreviewsResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "til.Note")
	proto.RegisterType((*NotePreview)(nil), "til.NotePreview")
	proto.RegisterType((*Pagination)(nil), "til.Pagination")
	proto.RegisterType((*PingRequest)(nil), "til.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "til.PingResponse")
	proto.RegisterType((*CreateNoteRequest)(nil), "til.CreateNoteRequest")
	proto.RegisterType((*GetNotePreviewsRequest)(nil), "til.GetNotePreviewsRequest")
	proto.RegisterType((*GetNotePreviewsResponse)(nil), "til.GetNotePreviewsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TilService service

type TilServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*Note, error)
	GetNotePreviews(ctx context.Context, in *GetNotePreviewsRequest, opts ...grpc.CallOption) (*GetNotePreviewsResponse, error)
}

type tilServiceClient struct {
	cc *grpc.ClientConn
}

func NewTilServiceClient(cc *grpc.ClientConn) TilServiceClient {
	return &tilServiceClient{cc}
}

func (c *tilServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/til.TilService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tilServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := grpc.Invoke(ctx, "/til.TilService/CreateNote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tilServiceClient) GetNotePreviews(ctx context.Context, in *GetNotePreviewsRequest, opts ...grpc.CallOption) (*GetNotePreviewsResponse, error) {
	out := new(GetNotePreviewsResponse)
	err := grpc.Invoke(ctx, "/til.TilService/GetNotePreviews", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TilService service

type TilServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateNote(context.Context, *CreateNoteRequest) (*Note, error)
	GetNotePreviews(context.Context, *GetNotePreviewsRequest) (*GetNotePreviewsResponse, error)
}

func RegisterTilServiceServer(s *grpc.Server, srv TilServiceServer) {
	s.RegisterService(&_TilService_serviceDesc, srv)
}

func _TilService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TilService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TilService_GetNotePreviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotePreviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).GetNotePreviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/GetNotePreviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).GetNotePreviews(ctx, req.(*GetNotePreviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TilService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "til.TilService",
	HandlerType: (*TilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TilService_Ping_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _TilService_CreateNote_Handler,
		},
		{
			MethodName: "GetNotePreviews",
			Handler:    _TilService_GetNotePreviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "til_service.proto",
}

func init() { proto.RegisterFile("til_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0xe9, 0x47, 0xc6, 0x09, 0x25, 0x2b, 0x28, 0xc6, 0x14, 0x35, 0xf8, 0x14, 0xf5,
	0x60, 0x4b, 0x41, 0x1c, 0xe8, 0xad, 0x70, 0x00, 0x2e, 0x55, 0x64, 0x7a, 0xb7, 0x36, 0xcd, 0xd4,
	0x5a, 0xc9, 0xf1, 0x2e, 0xde, 0x4d, 0x39, 0xc3, 0x5f, 0xe0, 0x8f, 0x21, 0xf1, 0x17, 0x10, 0x37,
	0xfe, 0x03, 0xda, 0xf1, 0x26, 0xb1, 0x48, 0x25, 0xe0, 0xc6, 0xcd, 0xf3, 0x76, 0xde, 0xec, 0x7b,
	0x6f, 0xd6, 0x30, 0xb2, 0xb2, 0xcc, 0x0d, 0xd6, 0xb7, 0xf2, 0x1a, 0x13, 0x5d, 0x2b, 0xab, 0x78,
	0xd7, 0xca, 0x32, 0x3a, 0x29, 0x94, 0x2a, 0x4a, 0x4c, 0x85, 0x96, 0xa9, 0xa8, 0x2a, 0x65, 0x85,
	0x95, 0xaa, 0x32, 0x4d, 0x4b, 0x74, 0xea, 0x4f, 0xa9, 0x9a, 0xaf, 0x6e, 0x52, 0x2b, 0x97, 0x68,
	0xac, 0x58, 0xea, 0xa6, 0x21, 0xfe, 0xca, 0xa0, 0x77, 0xa9, 0x2c, 0xf2, 0x7b, 0xd0, 0x91, 0x8b,
	0x90, 0x8d, 0xd9, 0xa4, 0x9b, 0x75, 0xe4, 0x82, 0x73, 0xe8, 0x55, 0x62, 0x89, 0x61, 0x67, 0xcc,
	0x26, 0xfd, 0x8c, 0xbe, 0x09, 0x53, 0x16, 0xc3, 0xae, 0xc7, 0x1c, 0x2f, 0x82, 0xc3, 0x1b, 0x59,
	0x22, 0xf5, 0xf6, 0x08, 0xdf, 0xd4, 0xfc, 0x25, 0xc0, 0x75, 0x8d, 0xc2, 0xe2, 0x22, 0x17, 0x36,
	0x7c, 0x30, 0x66, 0x93, 0x60, 0x1a, 0x25, 0x8d, 0xa4, 0x64, 0x2d, 0x29, 0xb9, 0x5a, 0x4b, 0xca,
	0xfa, 0xbe, 0xfb, 0xc2, 0x3a, 0xea, 0x4a, 0x2f, 0xd6, 0xd4, 0x87, 0x7f, 0xa6, 0xfa, 0xee, 0x0b,
	0x1b, 0xff, 0x60, 0x10, 0x38, 0x4b, 0xb3, 0x1a, 0x6f, 0x25, 0x7e, 0xfc, 0x2b, 0x67, 0xcf, 0x60,
	0xe0, 0xdc, 0xe4, 0xba, 0xe1, 0x78, 0x87, 0x41, 0xd5, 0x1a, 0xf3, 0xff, 0x19, 0x7d, 0x0b, 0x30,
	0x13, 0x85, 0xac, 0x68, 0xe3, 0xfc, 0x14, 0x02, 0x2d, 0x0a, 0xcc, 0xab, 0xd5, 0x72, 0x8e, 0xb5,
	0xf7, 0x0b, 0x0e, 0xba, 0x24, 0x84, 0x3f, 0x86, 0x43, 0x8d, 0x75, 0xee, 0x10, 0xf2, 0xbe, 0x97,
	0x1d, 0x68, 0xac, 0x67, 0xa2, 0xc0, 0x78, 0x08, 0xc1, 0x4c, 0x56, 0x45, 0x86, 0x1f, 0x56, 0x68,
	0x6c, 0x7c, 0x06, 0x83, 0xa6, 0x34, 0x5a, 0x55, 0x86, 0x76, 0x5c, 0xfb, 0x6f, 0x9a, 0xdb, 0xcf,
	0x36, 0x75, 0x3c, 0x85, 0xd1, 0x6b, 0x32, 0xe3, 0x22, 0xf7, 0x03, 0xf8, 0x53, 0xff, 0x50, 0x18,
	0xd9, 0xe9, 0x27, 0x56, 0x96, 0x09, 0x9d, 0x13, 0x1c, 0xbf, 0x83, 0xe3, 0x37, 0x68, 0x5b, 0x3b,
	0x32, 0x6b, 0x62, 0x0a, 0x4e, 0xb1, 0xb7, 0xe4, 0x83, 0x3c, 0x22, 0xfa, 0xd6, 0x69, 0xd6, 0x6a,
	0x89, 0x3f, 0x31, 0x78, 0xb4, 0x33, 0xcb, 0xcb, 0x7e, 0x01, 0xc3, 0xf6, 0x52, 0x4d, 0xc8, 0xc6,
	0xdd, 0x49, 0x30, 0xbd, 0xbf, 0x91, 0xe3, 0x19, 0xd9, 0xa0, 0xb5, 0x67, 0xf3, 0xcf, 0x1a, 0xa6,
	0x3f, 0x19, 0xc0, 0x95, 0x2c, 0xdf, 0x37, 0x3f, 0x27, 0x3f, 0x87, 0x9e, 0x4b, 0x8f, 0x37, 0xf7,
	0xb4, 0x72, 0x8d, 0x46, 0x2d, 0xc4, 0xc7, 0x37, 0xfc, 0xfc, 0xed, 0xfb, 0x97, 0xce, 0x01, 0xdf,
	0x4b, 0xb5, 0xe3, 0xbc, 0x02, 0xd8, 0xa6, 0xc9, 0x8f, 0xa9, 0x7f, 0x27, 0xde, 0x68, 0x1b, 0x68,
	0x3c, 0x22, 0x7e, 0x10, 0xef, 0xa7, 0xce, 0x83, 0x39, 0x67, 0x67, 0x3c, 0x87, 0xa3, 0xdf, 0x12,
	0xe1, 0x4f, 0x88, 0x70, 0x77, 0xe6, 0xd1, 0xc9, 0xdd, 0x87, 0x5e, 0xe0, 0xee, 0x05, 0xf3, 0x7d,
	0x7a, 0x96, 0xcf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x4a, 0xbc, 0xb5, 0x93, 0x04, 0x00,
	0x00,
}
