// Code generated by protoc-gen-go. DO NOT EDIT.
// source: til_service.proto

/*
Package til is a generated protocol buffer package.

It is generated from these files:
	til_service.proto

It has these top-level messages:
	PingRequest
	PingResponse
*/
package til

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "til.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "til.PingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TilService service

type TilServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type tilServiceClient struct {
	cc *grpc.ClientConn
}

func NewTilServiceClient(cc *grpc.ClientConn) TilServiceClient {
	return &tilServiceClient{cc}
}

func (c *tilServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/til.TilService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TilService service

type TilServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterTilServiceServer(s *grpc.Server, srv TilServiceServer) {
	s.RegisterService(&_TilService_serviceDesc, srv)
}

func _TilService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TilService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "til.TilService",
	HandlerType: (*TilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TilService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "til_service.proto",
}

func init() { proto.RegisterFile("til_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc9, 0xcc, 0x89,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e,
	0xc9, 0xcc, 0x51, 0xe2, 0xe5, 0xe2, 0x0e, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x51, 0xd2, 0xe2, 0xe2, 0x81, 0x70, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8,
	0x38, 0x8a, 0xa0, 0x6c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0xdf, 0xc8, 0x9a, 0x8b,
	0x2b, 0x24, 0x33, 0x27, 0x18, 0x62, 0xa6, 0x90, 0x2e, 0x17, 0x0b, 0x48, 0xa7, 0x90, 0x80, 0x5e,
	0x49, 0x66, 0x8e, 0x1e, 0x92, 0x99, 0x52, 0x82, 0x48, 0x22, 0x10, 0xad, 0x4a, 0x0c, 0x49, 0x6c,
	0x60, 0x37, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0x8c, 0xcf, 0x4d, 0x98, 0x00, 0x00,
	0x00,
}
