// Code generated by protoc-gen-go. DO NOT EDIT.
// source: til_service.proto

/*
Package til is a generated protocol buffer package.

It is generated from these files:
	til_service.proto

It has these top-level messages:
	Note
	PingRequest
	PingResponse
	CreateNoteRequest
*/
package til

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Note struct {
	Id        int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Note      string                      `protobuf:"bytes,3,opt,name=note" json:"note,omitempty"`
	Filename  string                      `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt *google_protobuf1.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Note) Reset()                    { *m = Note{} }
func (m *Note) String() string            { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()               {}
func (*Note) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Note) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Note) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Note) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Note) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Note) GetUpdatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PingResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type CreateNoteRequest struct {
	Note *Note `protobuf:"bytes,1,opt,name=note" json:"note,omitempty"`
}

func (m *CreateNoteRequest) Reset()                    { *m = CreateNoteRequest{} }
func (m *CreateNoteRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNoteRequest) ProtoMessage()               {}
func (*CreateNoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateNoteRequest) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

func init() {
	proto.RegisterType((*Note)(nil), "til.Note")
	proto.RegisterType((*PingRequest)(nil), "til.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "til.PingResponse")
	proto.RegisterType((*CreateNoteRequest)(nil), "til.CreateNoteRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TilService service

type TilServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*Note, error)
}

type tilServiceClient struct {
	cc *grpc.ClientConn
}

func NewTilServiceClient(cc *grpc.ClientConn) TilServiceClient {
	return &tilServiceClient{cc}
}

func (c *tilServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/til.TilService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tilServiceClient) CreateNote(ctx context.Context, in *CreateNoteRequest, opts ...grpc.CallOption) (*Note, error) {
	out := new(Note)
	err := grpc.Invoke(ctx, "/til.TilService/CreateNote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TilService service

type TilServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateNote(context.Context, *CreateNoteRequest) (*Note, error)
}

func RegisterTilServiceServer(s *grpc.Server, srv TilServiceServer) {
	s.RegisterService(&_TilService_serviceDesc, srv)
}

func _TilService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TilService_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TilServiceServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/til.TilService/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TilServiceServer).CreateNote(ctx, req.(*CreateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TilService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "til.TilService",
	HandlerType: (*TilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TilService_Ping_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _TilService_CreateNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "til_service.proto",
}

func init() { proto.RegisterFile("til_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0x34, 0x56, 0x33, 0xb5, 0x62, 0x16, 0x95, 0x10, 0x14, 0x4b, 0x4e, 0xa5, 0x87,
	0x04, 0xea, 0xc9, 0xde, 0xaa, 0x77, 0x91, 0xd8, 0x7b, 0xd9, 0x36, 0xdb, 0xb2, 0x90, 0x66, 0x63,
	0x76, 0xea, 0x03, 0x78, 0xf6, 0xe6, 0x8b, 0x09, 0xbe, 0x82, 0x0f, 0x22, 0x99, 0x6c, 0xda, 0x82,
	0x07, 0x6f, 0xfb, 0xff, 0xfb, 0xff, 0x99, 0x6f, 0x27, 0xe0, 0xa3, 0xca, 0xe7, 0x46, 0x56, 0x6f,
	0x6a, 0x29, 0xe3, 0xb2, 0xd2, 0xa8, 0x79, 0x07, 0x55, 0x1e, 0x5e, 0xaf, 0xb5, 0x5e, 0xe7, 0x32,
	0x11, 0xa5, 0x4a, 0x44, 0x51, 0x68, 0x14, 0xa8, 0x74, 0x61, 0x9a, 0x48, 0x78, 0x6b, 0x6f, 0x49,
	0x2d, 0xb6, 0xab, 0x04, 0xd5, 0x46, 0x1a, 0x14, 0x9b, 0xb2, 0x09, 0x44, 0x5f, 0x0c, 0xdc, 0x27,
	0x8d, 0x92, 0x9f, 0x81, 0xa3, 0xb2, 0x80, 0x0d, 0xd8, 0xb0, 0x93, 0x3a, 0x2a, 0xe3, 0x1c, 0xdc,
	0x42, 0x6c, 0x64, 0xe0, 0x0c, 0xd8, 0xd0, 0x4b, 0xe9, 0x4c, 0x9e, 0x46, 0x19, 0x74, 0xac, 0x57,
	0xf7, 0x42, 0x38, 0x59, 0xa9, 0x5c, 0x52, 0xd6, 0x25, 0x7f, 0xa7, 0xf9, 0x3d, 0xc0, 0xb2, 0x92,
	0x02, 0x65, 0x36, 0x17, 0x18, 0x5c, 0x0c, 0xd8, 0xb0, 0x37, 0x0e, 0xe3, 0x06, 0x29, 0x6e, 0x91,
	0xe2, 0x59, 0x8b, 0x94, 0x7a, 0x36, 0x3d, 0xc5, 0xba, 0xba, 0x2d, 0xb3, 0xb6, 0x7a, 0xf9, 0x7f,
	0xd5, 0xa6, 0xa7, 0x18, 0xf5, 0xa1, 0xf7, 0xac, 0x8a, 0x75, 0x2a, 0x5f, 0xb7, 0xd2, 0x60, 0x34,
	0x82, 0xd3, 0x46, 0x9a, 0x52, 0x17, 0x86, 0x80, 0x2b, 0x7b, 0xa6, 0xe7, 0x7a, 0xe9, 0x4e, 0x47,
	0x63, 0xf0, 0x1f, 0x09, 0xa1, 0x5e, 0x89, 0xfd, 0x00, 0xbf, 0xb1, 0xaf, 0x66, 0x04, 0xe1, 0xc5,
	0xa8, 0xf2, 0x98, 0xee, 0xc9, 0x1e, 0x7f, 0x30, 0x80, 0x99, 0xca, 0x5f, 0x9a, 0x5f, 0xc3, 0x27,
	0xe0, 0xd6, 0xe3, 0xf8, 0x39, 0xe5, 0x0e, 0x40, 0x42, 0xff, 0xc0, 0xb1, 0xf3, 0xfa, 0xef, 0xdf,
	0x3f, 0x9f, 0xce, 0x31, 0x3f, 0x4a, 0xca, 0xba, 0xf3, 0x00, 0xb0, 0x1f, 0xcf, 0xaf, 0x28, 0xff,
	0x87, 0x27, 0xdc, 0x13, 0x44, 0x3e, 0xf5, 0x7b, 0x51, 0x37, 0xa9, 0x51, 0xcc, 0x84, 0x8d, 0x16,
	0x5d, 0x5a, 0xce, 0xdd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x6a, 0x0a, 0x2e, 0x30, 0x02,
	0x00, 0x00,
}
